### ISSUE TITLE
ServiceDiscovery

### ISSUE THREAD

**Issue by obrassard** [cc-yvanross/log430-01-H22-documentation#9]
Le ServiceDiscovery est un service qui permet d'enregistrer et monitorer les micro-services de l'architecture. Il sera utilisé entre autre comme répertoire des ressources pour les autres micro-services et avec le ChaosMonkey (_implémenté par l'équipe 2_), dans une prochaine itération une interface utilisateur sera développée afin de pouvoir gérer les services manuellement. 

Ce que je pense c'est que le ServiceDiscovery recevra des appels d'enregistrement de la part des autres IService. En d'autres mots, lorsqu'un nouveau service va se connecter il devra s'enregistrer au ServiceDiscovery. 

> ⚠️ **À discuter, est-ce qu'on peut trouver un moyen de réduire le couplage entre chaque service et notre API. Est-ce qu'il y aurait une manière de découvrir dynamiquement les apis des autres ??**

### Rôles de ServiceDiscovery

* Conserver et mettre à jour la liste des services connectés et actifs, avec leur latence actuelle
   * Faire des health-check régulier sur les API pour enregistrer des logs d'activité.

* Conserver des logs des événnements (connexion et déconnexion des services, changement de latence etc)

* Mécanisme d'alerte en cas de problème (à discuter avec les autres teams)

Permet de vérifier l'état (health checks) de ces services de façon régulière. Permet ensuite aux autres services d'obtenir un répertoire des services actifs et en bonne santé.

## CoS

* Chaque microservice (IService) du réseau doit pouvoir s'enregistrer au ServiceDiscovery avec son URL, son numéro d'équipe, son nom et son type

* On peut obtenir la liste de tous les services actifs :
   * Pour chaque service on a besoin de retourner : 
      * Type
      * ID
      * Nom
      * Numéro d'équipe
      * URL
      * Latence actuelle
      * Date/heure de la connexion (up since..)
   * Avec des paramètres optionnels, on peut filtrer la liste des services selon : 
      * Le type
      * Le numéro d'équipe

* On peut obtenir la liste des évennements qui se sont produit pour un service particulier (avec son ID) :
   *  Pour chaque événement on doit retourner :
      * Date
      * Type (UP / DOWN / DEGRADATION / NORMAL)
      * Service concerné
   * ~Avec des paramètres optionnels, on peut filtrer la liste des services selon :~
      * ~Le type~
      * ~Le numéro d'équipe~
      *~L'ID du service~
      
* Périodiquement, la liste des services doit être mise à jour à l'aide du mécanisme ping / hearthbeat.
   * On doit mettre à jour la latence de chaque service et leur disponnibilité (up/down). 
   * On enregistre les changements d'états importants dans la liste d'événnements (logs).

    >  ⚠️ À discutter, je ne sais pas encore si on doit faire l'interraction dans les deux sens
IService -> DiscoveryService : heartbeat
DiscoveryService -> IService : ping

## Todos

- [x] Discuter de l'implémentation et bien définir les interfaces à implémenter (surtout ce que chaque service des autres équipes devra utiliser)
- [x] Discuter de la stratégie de persistance des données
- [x] Créer le modèle de BD
- [ ] Implémenter le service 
- [ ] Tester le service avec les outils de test Nest
- [ ] Documenter le service comme demandé dans l'énoncé du laboratoire

**Comment by obrassard** [comment]
Note : Le Service Discovery est lui aussi un `IService` donc il doit théoriquement s'auto enregistrer 🤔
